import type { Tool, Category } from "./types"

// Categories with their descriptions and icons
const categories: Category[] = [
  {
    id: "ai-assistants",
    name: "AI Assistants",
    description: "Virtual assistants powered by AI for various tasks and conversations",
    icon: "🤖",
    slug: "ai-assistants"
  },
  {
    id: "video-generation",
    name: "Video Generation",
    description: "Tools for creating and editing videos using AI capabilities",
    icon: "🎬",
    slug: "video-generation"
  },
  {
    id: "image-generation",
    name: "Image Generation",
    description: "Tools that create images and art from text descriptions",
    icon: "🎨",
    slug: "image-generation"
  },
  {
    id: "writing-grammar",
    name: "Writing & Grammar",
    description: "Tools for improving writing, grammar checking, and content creation",
    icon: "✍️",
    slug: "writing-grammar"
  },
  {
    id: "coding-development",
    name: "Coding & Development",
    description: "AI tools for software development, coding, and programming",
    icon: "💻",
    slug: "coding-development"
  },
  {
    id: "voice-audio",
    name: "Voice & Audio",
    description: "Tools for voice recognition, audio editing, and speech synthesis",
    icon: "🔊",
    slug: "voice-audio"
  },
  {
    id: "social-media",
    name: "Social Media",
    description: "AI tools for social media management, content, and analytics",
    icon: "📱",
    slug: "social-media"
  },
  {
    id: "productivity",
    name: "Productivity",
    description: "Tools to enhance workflow, organization, and efficiency",
    icon: "⚡",
    slug: "productivity"
  },
  {
    id: "marketing",
    name: "Marketing",
    description: "AI tools for digital marketing, campaigns, and automation",
    icon: "📈",
    slug: "marketing"
  },
  {
    id: "seo-tools",
    name: "SEO Tools",
    description: "AI-powered tools for search engine optimization and visibility",
    icon: "🔍",
    slug: "seo-tools"
  },
  {
    id: "customer-service",
    name: "Customer Service",
    description: "AI chatbots and tools for customer support and engagement",
    icon: "💬",
    slug: "customer-service"
  },
  {
    id: "email-assistants",
    name: "Email Assistants",
    description: "Tools for managing, composing, and optimizing emails",
    icon: "📧",
    slug: "email-assistants"
  },
]

// Sample AI tools data
const tools: Tool[] = [
  // AI Assistants
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "An AI language model developed by OpenAI that can generate human-like text based on the input it receives.",
    category: "ai-assistants",
    tags: ["Language Model", "Text Generation", "Conversational AI"],
    url: "https://chat.openai.com",
    rating: 5,
    pricing: "Free / Premium",
    features: ["Text generation", "Conversation", "Content creation", "Code assistance"],
    lastUpdated: "2023-10-15",
  },
  {
    id: "claude",
    name: "Claude",
    description: "Anthropic's conversational AI assistant designed to be helpful, harmless, and honest.",
    category: "ai-assistants",
    tags: ["Conversational AI", "Text Generation", "Research"],
    url: "https://claude.ai",
    rating: 5,
    pricing: "Free / Premium",
    features: ["Long context", "Document analysis", "Thoughtful responses", "Safety focused"],
    lastUpdated: "2023-11-20",
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "Google's multimodal AI assistant that can understand and process text, images, and other forms of data.",
    category: "ai-assistants",
    tags: ["Multimodal", "Search", "Google"],
    url: "https://gemini.google.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Web search", "Information synthesis", "Multimodal capabilities"],
    lastUpdated: "2023-12-10",
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "An AI assistant focused on providing accurate, cited information from across the web.",
    category: "ai-assistants",
    tags: ["Research", "Citations", "Information retrieval"],
    url: "https://perplexity.ai",
    rating: 4,
    pricing: "Free / Pro",
    features: ["Web search", "Citation", "Accuracy", "Research-oriented"],
    lastUpdated: "2023-09-05",
  },
  {
    id: "copilot",
    name: "Microsoft Copilot",
    description: "Microsoft's AI assistant that integrates with Microsoft 365 apps and Windows.",
    category: "ai-assistants",
    tags: ["Microsoft", "Office integration", "Windows"],
    url: "https://copilot.microsoft.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Office integration", "Creative writing", "Windows integration"],
    lastUpdated: "2023-08-15",
  },
  {
    id: "pi",
    name: "Pi",
    description: "An AI assistant designed for natural conversations and personal support.",
    category: "ai-assistants",
    tags: ["Personal assistant", "Conversation", "Coaching"],
    url: "https://pi.ai",
    rating: 3,
    pricing: "Free",
    features: ["Personal coaching", "Natural conversation", "Empathetic responses"],
    lastUpdated: "2023-07-22",
  },
  {
    id: "poe",
    name: "Poe",
    description: "A platform that provides access to multiple AI models in one place with a conversational interface.",
    category: "ai-assistants",
    tags: ["Multiple models", "Platform", "Quora"],
    url: "https://poe.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Multiple AI models", "Custom bots", "API access"],
    lastUpdated: "2023-06-14",
  },
  {
    id: "bing-chat",
    name: "Bing Chat",
    description: "Microsoft's AI-powered chat interface integrated with Bing search.",
    category: "ai-assistants",
    tags: ["Search", "Microsoft", "Bing"],
    url: "https://bing.com/chat",
    rating: 3,
    pricing: "Free",
    features: ["Web search", "Conversation", "Citation"],
    lastUpdated: "2023-05-30",
  },
  {
    id: "replika",
    name: "Replika",
    description: "An AI companion designed for friendly conversation and emotional support.",
    category: "ai-assistants",
    tags: ["Companion", "Emotional support", "Personalized"],
    url: "https://replika.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Personalized conversation", "Emotional support", "Relationship building"],
    lastUpdated: "2023-04-25",
  },
  {
    id: "character-ai",
    name: "Character.AI",
    description: "Platform for creating and chatting with AI characters with distinct personalities.",
    category: "ai-assistants",
    tags: ["Characters", "Roleplay", "Conversation"],
    url: "https://character.ai",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Character creation", "Roleplay", "Community"],
    lastUpdated: "2023-03-18",
  },
  
  // Video Generation
  {
    id: "synthesia",
    name: "Synthesia",
    description: "AI video generation platform that creates videos with virtual avatars from text.",
    category: "video-generation",
    tags: ["Video Creation", "Avatars", "Text-to-Video"],
    url: "https://www.synthesia.io",
    rating: 5,
    pricing: "Subscription",
    features: ["AI avatars", "Multiple languages", "Custom backgrounds", "Script editing"],
    lastUpdated: "2023-11-05",
  },
  {
    id: "runway",
    name: "Runway",
    description: "Creative toolkit with AI video editing, effects, and generation capabilities.",
    category: "video-generation",
    tags: ["Video Editing", "Motion Graphics", "Creative Tools"],
    url: "https://runwayml.com",
    rating: 5,
    pricing: "Subscription",
    features: ["Gen-2 video generation", "Motion brush", "Inpainting", "Green screen"],
    lastUpdated: "2023-10-12",
  },
  {
    id: "d-id",
    name: "D-ID",
    description: "Platform for creating talking head videos from text using AI avatars.",
    category: "video-generation",
    tags: ["Talking Heads", "Avatars", "Presentation"],
    url: "https://www.d-id.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Avatar customization", "Text-to-speech", "Speaking portrait creation"],
    lastUpdated: "2023-09-28",
  },
  {
    id: "lumen5",
    name: "Lumen5",
    description: "AI-powered video creation platform that turns blog posts and text into engaging videos.",
    category: "video-generation",
    tags: ["Content Repurposing", "Marketing Videos", "Social Media"],
    url: "https://lumen5.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Text to video", "Stock media library", "Brand customization", "AI scene generation"],
    lastUpdated: "2023-11-15",
  },
  {
    id: "deepbrain",
    name: "DeepBrain AI",
    description: "Platform for creating AI avatars and human-like digital presenters for videos.",
    category: "video-generation",
    tags: ["AI Avatars", "Presenters", "Corporate Videos"],
    url: "https://www.deepbrain.io",
    rating: 4,
    pricing: "Subscription",
    features: ["Realistic AI presenters", "Multiple languages", "Custom script generation"],
    lastUpdated: "2023-10-18",
  },
  {
    id: "invideo",
    name: "InVideo",
    description: "Online video creation platform with AI-powered templates and editing tools.",
    category: "video-generation",
    tags: ["Video Editor", "Templates", "Marketing"],
    url: "https://invideo.io",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Pre-made templates", "Text to video", "Media library", "Automated voiceovers"],
    lastUpdated: "2023-09-12",
  },
  {
    id: "elai",
    name: "Elai.io",
    description: "AI video generation platform that creates videos from text without any video production skills.",
    category: "video-generation",
    tags: ["Text to Video", "AI Presenters", "No-code"],
    url: "https://elai.io",
    rating: 4,
    pricing: "Subscription",
    features: ["AI presenters", "Custom backgrounds", "Multi-language support"],
    lastUpdated: "2023-08-30",
  },
  
  // Image Generation
  {
    id: "midjourney",
    name: "Midjourney",
    description: "AI art generator that creates images from textual descriptions.",
    category: "image-generation",
    tags: ["Art Generation", "Text-to-Image", "Creative"],
    url: "https://www.midjourney.com",
    rating: 5,
    pricing: "Subscription",
    features: ["High-quality images", "Style variations", "Discord integration"],
    lastUpdated: "2023-12-01",
  },
  {
    id: "dall-e",
    name: "DALL-E",
    description: "OpenAI's text-to-image model that generates images from natural language descriptions.",
    category: "image-generation",
    tags: ["Text-to-Image", "OpenAI", "Creative"],
    url: "https://openai.com/dall-e-3",
    rating: 5,
    pricing: "Credits / Subscription",
    features: ["Detailed prompts", "Outpainting", "Variations", "Editing"],
    lastUpdated: "2023-11-25",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    description: "Open-source text-to-image model that can run locally or through various interfaces.",
    category: "image-generation",
    tags: ["Open Source", "Text-to-Image", "Customizable"],
    url: "https://stability.ai",
    rating: 4,
    pricing: "Free / Premium Services",
    features: ["Local installation", "Model fine-tuning", "Community extensions"],
    lastUpdated: "2023-10-30",
  },
  
  // Writing & Grammar
  {
    id: "grammarly",
    name: "Grammarly",
    description: "AI writing assistant that helps with grammar, clarity, and writing style.",
    category: "writing-grammar",
    tags: ["Grammar", "Editing", "Writing Assistant"],
    url: "https://www.grammarly.com",
    rating: 5,
    pricing: "Free / Premium",
    features: ["Grammar checking", "Style suggestions", "Tone detection", "Plagiarism detection"],
    lastUpdated: "2023-12-05",
  },
  {
    id: "jasper",
    name: "Jasper",
    description: "AI content platform that helps create marketing copy, blog posts, and other content.",
    category: "writing-grammar",
    tags: ["Content Creation", "Marketing", "Copywriting"],
    url: "https://www.jasper.ai",
    rating: 4,
    pricing: "Subscription",
    features: ["Templates", "Long-form assistant", "SEO mode", "Brand voice"],
    lastUpdated: "2023-11-18",
  },
  {
    id: "quillbot",
    name: "QuillBot",
    description: "AI-powered paraphrasing tool that helps rewrite and enhance text.",
    category: "writing-grammar",
    tags: ["Paraphrasing", "Summarization", "Grammar"],
    url: "https://quillbot.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Paraphraser", "Grammar checker", "Summarizer", "Citation generator"],
    lastUpdated: "2023-11-10",
  },
  {
    id: "wordtune",
    name: "Wordtune",
    description: "AI writing companion that helps rewrite, rephrase, and reword your text.",
    category: "writing-grammar",
    tags: ["Rewriting", "Rephrasing", "Tone Adjustment"],
    url: "https://www.wordtune.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Rewriting", "Tone adjustment", "Sentence expansion", "Shortening"],
    lastUpdated: "2023-10-22",
  },
  {
    id: "hemingwayapp",
    name: "Hemingway Editor",
    description: "Writing tool that helps make your writing bold and clear by highlighting complex sentences.",
    category: "writing-grammar",
    tags: ["Readability", "Editing", "Simplification"],
    url: "https://hemingwayapp.com",
    rating: 4,
    pricing: "Free / One-time purchase",
    features: ["Readability analysis", "Sentence complexity detection", "Adverb identification"],
    lastUpdated: "2023-07-15",
  },
  {
    id: "sudowrite",
    name: "Sudowrite",
    description: "AI writing tool designed specifically for fiction writers and creative writing.",
    category: "writing-grammar",
    tags: ["Creative Writing", "Fiction", "Story Generation"],
    url: "https://www.sudowrite.com",
    rating: 4,
    pricing: "Subscription",
    features: ["Story brainstorming", "Character development", "Description generation"],
    lastUpdated: "2023-09-08",
  },
  {
    id: "prowritingaid",
    name: "ProWritingAid",
    description: "Grammar checker, style editor, and writing mentor in one package.",
    category: "writing-grammar",
    tags: ["Grammar", "Style", "Writing Improvement"],
    url: "https://prowritingaid.com",
    rating: 4,
    pricing: "Subscription",
    features: ["Grammar checking", "Style analysis", "Readability metrics", "Writing reports"],
    lastUpdated: "2023-08-25",
  },
  
  // Coding & Development
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "AI pair programmer that suggests code completions based on context.",
    category: "coding-development",
    tags: ["Coding Assistant", "Pair Programming", "Suggestions"],
    url: "https://github.com/features/copilot",
    rating: 5,
    pricing: "Subscription",
    features: ["Code completion", "Multiple languages", "IDE integration", "Natural language to code"],
    lastUpdated: "2023-12-10",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Platform for building, training and deploying state-of-the-art machine learning models.",
    category: "coding-development",
    tags: ["Machine Learning", "NLP", "Model Deployment"],
    url: "https://huggingface.co",
    rating: 5,
    pricing: "Free / Enterprise",
    features: ["Model hosting", "Dataset management", "ML collaboration"],
    lastUpdated: "2023-09-20",
  },
  {
    id: "cursor",
    name: "Cursor",
    description: "AI-first code editor that helps developers write, understand, and fix code faster.",
    category: "coding-development",
    tags: ["Code Editor", "AI Assistant", "Productivity"],
    url: "https://cursor.sh",
    rating: 5,
    pricing: "Free / Premium",
    features: ["Code completion", "AI chat in editor", "Code explanation", "Bug fixing"],
    lastUpdated: "2023-11-28",
  },
  {
    id: "tabnine",
    name: "Tabnine",
    description: "AI code completion assistant that helps developers code faster with whole-line and full-function code completions.",
    category: "coding-development",
    tags: ["Code Completion", "IDE Integration", "Productivity"],
    url: "https://www.tabnine.com",
    rating: 4,
    pricing: "Free / Team / Enterprise",
    features: ["Code completions", "Multiple IDE support", "Private code models"],
    lastUpdated: "2023-10-05",
  },
  {
    id: "codeium",
    name: "Codeium",
    description: "Free AI-powered code completion tool that integrates with many IDEs and supports multiple languages.",
    category: "coding-development",
    tags: ["Code Completion", "Free", "IDE Integration"],
    url: "https://codeium.com",
    rating: 4,
    pricing: "Free / Team",
    features: ["Code completions", "Natural language search", "Code explanation"],
    lastUpdated: "2023-09-15",
  },
  {
    id: "codex",
    name: "OpenAI Codex",
    description: "AI system that translates natural language to code across many programming languages.",
    category: "coding-development",
    tags: ["Natural Language to Code", "OpenAI", "API"],
    url: "https://openai.com/blog/openai-codex",
    rating: 5,
    pricing: "API Usage",
    features: ["Language to code", "Multiple programming languages", "Code explanation"],
    lastUpdated: "2023-08-20",
  },
  {
    id: "replit-ghostwriter",
    name: "Replit Ghostwriter",
    description: "AI pair programmer integrated directly into Replit's development environment.",
    category: "coding-development",
    tags: ["Pair Programming", "Code Generation", "Productivity"],
    url: "https://replit.com/ghostwriter",
    rating: 4,
    pricing: "Subscription",
    features: ["Code generation", "Debugging assistance", "Explanation", "Online IDE integration"],
    lastUpdated: "2023-10-12",
  },
  
  // Voice & Audio
  {
    id: "descript",
    name: "Descript",
    description: "All-in-one audio/video editing platform with AI-powered features like text-based editing and voice cloning.",
    category: "voice-audio",
    tags: ["Audio Editing", "Voice Cloning", "Transcription"],
    url: "https://www.descript.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Text-based editing", "Voice cloning", "Transcription", "Studio sound"],
    lastUpdated: "2023-11-15",
  },
  
  // Design / Other categories
  {
    id: "canva",
    name: "Canva",
    description: "Design platform with AI-powered features for creating graphics, presentations, and visual content.",
    category: "productivity",
    tags: ["Graphic Design", "Templates", "Visual Content"],
    url: "https://www.canva.com",
    rating: 5,
    pricing: "Free / Premium",
    features: ["Design templates", "AI image generation", "Collaboration"],
    lastUpdated: "2023-10-05",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "AI writing assistant integrated into Notion that helps you draft, edit, summarize, and brainstorm content.",
    category: "productivity",
    tags: ["Writing Assistant", "Note-taking", "Productivity"],
    url: "https://www.notion.so/product/ai",
    rating: 4,
    pricing: "Subscription (addon)",
    features: ["Writing assistance", "Summarization", "Content generation"],
    lastUpdated: "2023-08-10",
  },
  {
    id: "krisp",
    name: "Krisp",
    description: "AI-powered noise cancellation app that removes background noise and echo from calls.",
    category: "productivity",
    tags: ["Noise Cancellation", "Audio", "Meetings"],
    url: "https://krisp.ai",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Noise cancellation", "Echo removal", "Voice enhancement"],
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    description: "AI copywriting tool that generates marketing copy, social media content, and more.",
    category: "marketing",
    tags: ["Copywriting", "Marketing", "Content Creation"],
    url: "https://www.copy.ai",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Marketing copy", "Social media content", "Email writing"],
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    description: "AI-powered meeting assistant that records, transcribes, and summarizes conversations in real-time.",
    category: "productivity",
    tags: ["Transcription", "Meeting Assistant", "Notes"],
    url: "https://otter.ai",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Transcription", "Meeting summaries", "Collaboration"],
  },
  {
    id: "tableau",
    name: "Tableau",
    description: "Data visualization software with AI capabilities for business intelligence and analytics.",
    category: "research",
    tags: ["Data Visualization", "Analytics", "Business Intelligence"],
    url: "https://www.tableau.com",
    rating: 5,
    pricing: "Subscription",
    features: ["Data visualization", "Analytics", "Dashboard creation"],
  },
  // Email Assistants Tools
  {
    id: "superhuman",
    name: "Superhuman",
    description: "Email client with AI-powered features that helps you work through your inbox twice as fast.",
    category: "email-assistants",
    tags: ["Email Client", "Productivity", "AI Features"],
    url: "https://superhuman.com",
    rating: 5,
    pricing: "Subscription",
    features: ["Split inbox", "AI triage", "Undo send", "Follow-up reminders"],
    lastUpdated: "2023-12-01",
  },
  {
    id: "flowrite",
    name: "Flowrite",
    description: "AI writing tool that turns short instructions into ready-to-send emails and messages.",
    category: "email-assistants",
    tags: ["Email Writing", "Templates", "Productivity"],
    url: "https://www.flowrite.com",
    rating: 4,
    pricing: "Subscription",
    features: ["Email generation", "Tone adjustment", "Browser extension"],
    lastUpdated: "2023-11-05",
  },
  {
    id: "lavender",
    name: "Lavender",
    description: "Email AI assistant that helps you write better emails that get responses.",
    category: "email-assistants",
    tags: ["Email Coaching", "Response Rate", "Analysis"],
    url: "https://www.lavender.ai",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Email scoring", "Writing suggestions", "Response time predictions"],
    lastUpdated: "2023-10-18",
  },
  {
    id: "sanebox",
    name: "SaneBox",
    description: "Email management tool that uses AI to filter unimportant emails out of your inbox.",
    category: "email-assistants",
    tags: ["Email Management", "Priority Inbox", "Decluttering"],
    url: "https://www.sanebox.com",
    rating: 4,
    pricing: "Subscription",
    features: ["Email filtering", "Follow-up reminders", "Attachment saving"],
    lastUpdated: "2023-09-10",
  },
  {
    id: "gmelius",
    name: "Gmelius",
    description: "Gmail enhancement suite with AI features for email collaboration and automation.",
    category: "email-assistants",
    tags: ["Gmail", "Collaboration", "Automation"],
    url: "https://gmelius.com",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Email templates", "Shared inboxes", "Email sequences", "CRM integration"],
    lastUpdated: "2023-08-22",
  },
  {
    id: "mailbutler",
    name: "Mailbutler",
    description: "Email productivity tool with smart AI features for Apple Mail, Gmail, and Outlook.",
    category: "email-assistants",
    tags: ["Email Productivity", "Scheduling", "Tracking"],
    url: "https://www.mailbutler.io",
    rating: 4,
    pricing: "Free / Premium",
    features: ["Email tracking", "Scheduling", "Templates", "Follow-up reminders"],
    lastUpdated: "2023-07-15",
  },
]

// Function to get all tools
export async function getAllTools(): Promise<Tool[]> {
  // In a real application, this would fetch from an API or database
  return tools
}

// Function to get tools by category
export async function getToolsByCategory(categoryId: string): Promise<Tool[]> {
  return tools.filter((tool) => tool.category === categoryId)
}

// Function to get a single tool by ID
export async function getToolById(id: string): Promise<Tool | undefined> {
  return tools.find((tool) => tool.id === id)
}

// Function to get all categories
export async function getCategories(): Promise<Category[]> {
  return categories
}

// Function to get a single category by ID
export async function getCategoryById(id: string): Promise<Category | undefined> {
  return categories.find((category) => category.id === id)
}
